### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by achikin** [oakmac/parinfer-viml#7]
I've installed the plugin via vim-plug, opened Clojure file, but nothing happens. What should I do to activate the plugin?

**Comment by oakmac** [comment]
From the README:

> Please note that this project is solely for the library that implements the core Parinfer algorithm; it is not a vi extension that can be used for editing.

You may wish to check out [nvim-parinfer](https://github.com/snoe/nvim-parinfer.js) or [vim-parinfer](https://github.com/bhurlow/vim-parinfer) projects.
